# -*- coding: utf-8 -*-
"""Sist. Distribuidos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvtTxfEcaXUOLlA-0gjujYSstXGFmnMW

Exercicios parte 2
"""

#ex: 1

import requests
url = 'https://viacep.com.br/ws/'
cep = '30140071'
formato = '/xml/'
r = requests.get(url + cep + formato)
if (r.status_code == 200):
  print()
  print('JSON : ', r.text)
  print()
else:
  print('Nao houve sucesso na requisicao.')

#ex 2

import requests
url = 'https://viacep.com.br/ws/'
ceps = ['30140071', '30140072', '30140073', '30140074', '30140075']
formato = '/xml/'

for cep in ceps:

  r = requests.get(url + cep + formato)

  if (r.status_code == 200):
    print()
    print('JSON : ', r.text)
    print()

  else:
    print('Nao houve sucesso na requisicao.')

#ex: 3
import requests
url = 'https://viacep.com.br/ws/'
ceps = ['30140071', '30140072', '30140073', '30140074', '30140075']
formato = '/json/'

for cep in ceps:

  r = requests.get(url + cep + formato)

  if (r.status_code == 200):
    print()
    print('JSON : ', r.text)
    print()

  else:
    print('Nao houve sucesso na requisicao.')

#4 
import requests
url = 'https://viacep.com.br/abc/'
cep = '30140071'
formato = '/json/'
r = requests.get(url)
if (r.status_code == 200):
 print()
 print('JSON : ', r.json())
 print()
else:
 print('Nao houve sucesso na requisicao.')

#ex: 5

import requests
r = requests.get('http://www.google.com/search', params={'q':
'Protocolo HTTP'})

def salvar_arquivo_html(texto_html):
  arquivo = open('resultado_busca.html', 'w')
  arquivo.write(texto_html)
  arquivo.close()
  
  
  
if (r.status_code == 200):
 print()
 print('Retorno : ', r.text)
 salvar_arquivo_html(r.text)
 print()
else:
 print('Nao houve sucesso na requisicao.')